Issue/12
InoueErika/lamp_practice pull request #15
Opened 2021-01-09 14:56 UTC by InoueErika

Issue/14
グルーピングして購入履歴の合計金額（idごと）を表示する。

2021-01-09 15:27 UTC, primestyleus requested changes
@InoueErika 
get_purchase_historyでPurchase_detailsをJOIN
JOINしたところまではあっています。ただ、前回説明したようにGroupByやSUMを使わないとこの課題は解けません。現時点で履歴画面で同じ注文番号で複数の行が出てくる箇所があると思います。1つの注文につき、1行で表示が正しい動作となります。もう少し頑張ってみましょう。

2021-01-10 14:07 UTC, InoueErika commented
@primestyleus 
合計金額の出し方について質問です。
注文履歴を一行ずつ表示させることができましたが、priceをそのままSUMしてしまうと、
amountが無視された金額が表示されてしまうので、Purchase_detailsに新しくsum_priceというカラムを作成しました。
sum_priceにはprice×amountの金額を表示させてsum_priceをSUMした金額を合計金額とする、という考え方で合っていますか？
？

2021-01-10 14:12 UTC, primestyleus requested changes
@InoueErika 
大枠としてはあっていますが、sum_priceというカラムを追加することは正規化の考えからは外れてしまいます。（計算で求まるものはカラムとして定義しない）SUM()のかっこの中には計算式をそのままわたすこともできます。あともう一息だとおもいます。がんばりましょう。

2021-01-10 22:58 UTC, primestyleus reviewed
@InoueErika 
うまくSUMとGroup Byを使うことができましたね！SUMとともにASを使うことでさらにコードをスッキリさせることができますが、そこはすぐに対応しなくてもよいです。

あとは
・購入履歴が新しいものから順番に表示する
・管理者のときにユーザIDを指定せずに全履歴を取得する
・詳細画面に遷移するためのボタンを表示
ができれば、履歴画面は完成になります。

同じIssueで進めていただいてよいので、こちらはマージせずにそのままにしておきます。

2021-01-11 13:49 UTC, InoueErika commented
@primestyleus 
管理者のときにユーザIDを指定せずに全履歴を取得について質問です。
if(is_admin($user))を使ってみましたが動作しません。
164行目のif文さえ合っていれば正しく実装されるのでしょうか？

2021-01-11 13:51 UTC, primestyleus reviewed
@InoueErika 
管理者のときに処理を分けるのはうまくできていますね。気になる箇所にコメントしているので参考にしてください。うまくいっていない部分の解決につながるかと思います。
あとは詳細画面に遷移するボタンの設置でしょうか。続きも頑張って進めてください。

2021-01-11 13:51 UTC, primestyleus commented on www/html/purchase_history.php
> +$histories = array_reverse($histories);
@InoueErika 
この方法でも確かにできますが、並び順の指定はSQLで行ったほうがよいので、その方法も調べてみてください。

2021-01-11 13:51 UTC, primestyleus commented on www/model/cart.php
> +    $params = [$user_id];
@InoueErika 
管理者の場合はデータバインドもしないので（SQL文中に？がないので）$paramsの指定も不要です。

2021-01-11 14:14 UTC, InoueErika commented on www/html/purchase_history.php
> +$histories = array_reverse($histories);
@primestyleus 
ORDER BY id DESCを追加してみたらうまくいきました

2021-01-11 14:17 UTC, InoueErika commented on www/model/cart.php
> +    $params = [$user_id];
@primestyleus 
$params = [$user_id]を削除、fetch_all_query($db, $sql)にしましたが、
if(is_admin($user))がどうしても動作しません。
elseの方は問題なく動作しています。

2021-01-13 00:47 UTC, primestyleus commented on www/model/cart.php
> +    $params = [$user_id];
@InoueErika 
そうですか、どんなエラーメッセージが出てきますか？
SQL文を直接phpMyAdminで実行すると問題なく結果が表示されますか？

2021-01-13 01:17 UTC, primestyleus requested changes
@InoueErika 
基本OKです！幾つか不要なコードが残っているのでそこだけ削除対応をお願いします。

2021-01-13 01:17 UTC, primestyleus commented on www/html/purchase_details.php
> +$histories = get_purchase_history($db, $user);
正しく$historyを取得できているので、すべてをとってくる$historiesは不要です。この行は削除しておきましょう。

2021-01-13 01:17 UTC, primestyleus commented on www/model/cart.php
> +  $db->beginTransaction();
SELECT文ではトランザクションは不要ですので、commit/rollbackとあわせて削除しておきましょう。

2021-01-13 04:01 UTC, merged